### ISSUE TITLE
have you looked at KaTeX for math typesetting

### ISSUE THREAD

**Issue by ghost** [Wikunia/Javis.jl#176]
https://github.com/KaTeX/KaTeX
https://katex.org

**Comment by Wikunia** [comment]
Kind of :smile: Do you have an idea how to integrate it with Julia?

**Comment by qlcom** [comment]
> Do you have an idea how to integrate it with Julia?

sorry, i can't help on that. I haven't started learning Julia yet.

**Comment by TheCedarPrince** [comment]
Thanks for opening an issue @qlcom !

@Wikunia ,there does seem to be some work being done to bring KaTeX into Julia as evidenced here: https://github.com/piever/KaTeX.jl

@qlcom - what benefit do you see using KaTeX instead of our current LaTeX solution? Just curious here as though I am familiar with KaTeX, I just don't know why we might want to replace LaTeX.

**Comment by qlcom** [comment]
> I just don't know why we might want to replace LaTeX

KaTex renders TeX expression. TeX functions supported by KaTeX - https://katex.org/docs/supported.html

**Comment by TheCedarPrince** [comment]
Good point, we'll look into it at some time! Thanks again @qlcom :smile:
