### ISSUE TITLE
Jupyter Support and Integration

### ISSUE THREAD

**Issue by TheCedarPrince** [Wikunia/Javis.jl#207]
**Is your feature request related to a problem? Please explain.**

Currently, Javis does not work within a Jupyter environment (be it lab or notebook). One cannot use Javis to view frames of an animation easily like they could using the built-in Javis image viewer. Furthermore, on some platforms, the Javis image viewer is not performant due to it being built using Gtk.jl. 

We could perhaps get around this performance issue as well by providing browser-based support built around using Jupyter as a platform.

**Describe the solution you'd like**

I would love to build functionality into Javis Jupyter notebook support by creating something like this:

![sliderplot](https://user-images.githubusercontent.com/29561456/94599680-cc239f00-025e-11eb-9b6c-c4124f300c9f.gif)

> Source: https://blog.dominodatalab.com/interactive-dashboards-in-jupyter/

I think this functionality could be achieved by using [Interact.jl](https://github.com/JuliaGizmos/Interact.jl). Furthermore, this might be better suited to go into its own repository. So, initial development may take place on the main branch but later move to its own dedicated location. 

**Describe alternatives you've considered**

The best alternative would be the Javis image viewer but since not all platforms best support GTK based GUIs, this would provide greater applicability of Javis.

**Comment by TheCedarPrince** [comment]
See this to show gif in Jupyter: https://www.reddit.com/r/Julia/comments/iqp5cr/adding_the_power_of_animationsjl_to_javisjl_v02/

**Comment by Sov-trotter** [comment]
The idea for a dedicated packge to view stuff sounds pretty cool(a similar example is https://github.com/JuliaAstro/AstroImageView.jl). which serves like a frontend for the JuliaAstro image processing tools. If we need that sort of complex functionality for Javis in the future, it's a good way to go ahead. In which case I think a more general "LuxorViewer.jl" package makes more sense since that will automatically support Javis.

**Comment by Sov-trotter** [comment]
I also tried to look into Interact.jl side, the code to replicat the gtk functionality is pretty much simple. The only place where I seem to be stuck is rendering the frame matrix in the cell. 
I tried to reuse @TheCedarPrince 's code 
```julia
Interact.@manipulate for f in 1:length(frames)
        fr = get_javis_frame(video, actions, f)
        # colorview(RGB, fr)
        
        frame_mat = transpose(fr)
        s = CairoImageSurface(frame_mat)
        context = Javis.Luxor.Cairo.creategc(s)
        
        image(context, s, 0, 0, video.width, video.height)
    end
```
But it returns `Nothing`. MAaybe something I am missing here? Or is Cairo not supported for Jupyter.
Also since Javis has a Images.jl dependecy, I tried using the `Images.colorview` method to render the image but the `Javis.get_javis_frame` method returns a `Array{ARGB, 2}`, and I am not sure I we can get Images to deal with that without some conversions which might make the viewer slow?
