### ISSUE TITLE
Change arguments of an Action

### ISSUE THREAD

**Issue by Wikunia** [Wikunia/Javis.jl#216]
**Is your feature request related to a problem? Please explain.**
Currently each action has access to `video, action, frame` but maybe the user would like to change a parameter.
We can use scaling for changing the radius of a circle as an example but maybe one would like to draw a line that gets longer for some frames which can currently be done hard coded with `frame` but that's not intuitive.

**Describe the solution you'd like**
One option would be:
```julia
Action(1:100, (args...; x=0, y=0)->draw_line(O, Point(x, y)); subactions=[
     SubAction(10:50, change(:x=>100))
])
```
So one can define keyword arguments that can be changed in an animated way. The change would always be from the last value to the next. I'm not sure whether Javis has internally access to the `x=0` though :thinking: 
I think we need `:x` as `x` itself is not defined.

**Describe alternatives you've considered**
If we don't have access to the default value we can maybe use:
```julia
change(:x, 0, 100)
```
or 
```julia
change(:x, 0 => 100)
```

**Additional context**
In general this should of course also work with Animations.jl such that one can write an `Animation` and just call `change(:x)` to apply that change to the variable x.

**Comment by Wikunia** [comment]
Seems like it's not that easy to or even possible to get access to the default value.

**Comment by codejaeger** [comment]
> Seems like it's not that easy to or even possible to get access to the default value.

@Wikunia This turns out to be a bug with respect to documentation for the [change](https://github.com/Wikunia/Javis.jl/blob/4ef1ee7e12b452fb49dc9e47eca312f7648b591c/src/action_animations.jl#L402) function. I also tried to look for a way to extract the defaults from the keyword arguments but no success yet. Apart from that, I think the other issue this feature might help to solve is passing relevant keywords to drawing functions. Pulling in issue #313, if multiple draw functions are to be composed together to form the object drawing function then it makes sense to let the individual draw functions access keywords only specific to their purpose.
.

**Comment by Wikunia** [comment]
Can you clarify what you mean? I can't see anything wrong with the docstring for the `change` function. It either sets a value without animation or animates when a pair of values is given. I also don't understand the second part of your point can you give an example?

**Comment by codejaeger** [comment]
Sorry I termed it as a bug, it is actually more of a feature request 😄 . My assumption was that `change` would interpolate between the present default value used in the drawing function and the new value passed. Now I see it clearly mentioned in the docstrings, apologies! If the change keyword is not available to the object then I presume interpolating is difficult.

I was trying out a way around for issue 313. Consider the following
 ```julia
function Line(p1, p2)
   return (args...; line_width=12) -> custom_line(p1, p2, line_width)
end
function Circle(r)
   return (args...; radius=r) -> circle(O, radius, :fill)
end

obj = Object(1:50, [Line(p1, p2), Circle(r)])
```
Now, animating the line using `line_width` and circle via `radius` would lead to an error since all the change arguments are passed to the drawing function. Again, it is not decided yet how the multiple draw functions will be implemented but I guess the issue would result nonetheless.

**Comment by codejaeger** [comment]
The reason I mentioned it in this thread is since, if there is a way to know what keywords a particular drawing function requires it will be possible to store the default from the change keywords themselves. Then probably interpolation could be done for a subset of keywords using `change(:radius, 13)`.

**Comment by Wikunia** [comment]
One thing that would make this possible is to introduce a macro which then takes the defaults and writes them into the object metadata or similar. 
The problem is that we would loose some dispatch functionality for the Object.
