### ISSUE TITLE
Let a shape, text, whatever appear

### ISSUE THREAD

**Issue by Wikunia** [Wikunia/Javis.jl#43]
I think it would be nice to let something be drawn like a polygon line by line or let it appear from the background by blending in.
Blending in can be change in opacity or line thickness.

**Comment by Wikunia** [comment]
It feels like we need #44 for that @TheCedarPrince ?
Or how else shall the user define appear and disappear?
```
Action(1:100, func, Appear(10), Disappear(10))
```
which means Appear in the first 10 frames then stay and disappear in the last ten might work but with subactions this will be much cleaner.

**Comment by TheCedarPrince** [comment]
I agree - I think we may want to wait until we have subactions functioning and then implement this fully. I think that without subactions, this sort of call looks strange and not intuitive. Now that we also have #47 implemented, I am excited because I think things are going to start looking much cleaner when we also implement subactions.

**Comment by Wikunia** [comment]
Shall I change the milestone of #44 to v0.1.0 or this one to v0.2.0? If I change this one basically only tutorial is missing from v0.1.0 so I tend to implement SubActions earlier ;)

**Comment by TheCedarPrince** [comment]
Yea, change it to v0.1.0.
