### ISSUE TITLE
Animate object step by step

### ISSUE THREAD

**Issue by Wikunia** [Wikunia/Javis.jl#44]
This is a bit out of #43 
Currently it's only possible do define an Animation like between frame 1:100 draw a line and then we can define and maybe get the position of the line back to do something with it. 
It might make sense in same cases to define an Action like this:

```
Action(1:70, draw_line, SubAction(10, appear), SubAction(50, Translate(50, 50)), SubAction(10, disappear)
```

Where a `SubAction` gets a number of frames and a function so here it would appear for 10 frames then translate the line for 50 frames and then disappear in the last 10 frames.

Does that make sense @TheCedarPrince ?

**Comment by TheCedarPrince** [comment]
Oh you put into words what I was trying to say in #33! This makes a lot of sense. I spent some time thinking about this and my only concern is that you could end up having Action calls that span multiple lines with SubActions being called within each Action. I think this is ok but I feel like there should be a cleaner way to handle a `SubAction`.

This might actually be the best way of handling it because I am opposed to adding another kwarg to the overarching `javis` function for subactions. But, I think having `Action` have a `subactions` kwarg I think is fine. Furthermore, what I like about this particular set-up is that reading the code I think would be very linear and straightforward. What I see in my mind is code looking like this:

```julia
 function ground(args...) 
      background("white")
      sethue("black")
  end
  
  function circ(p=O, color="black")
      sethue(color)
      circle(p, 25, :fill)
      return Transformation(p, 0.0)
  end
  
  demo = Video(500, 500)
  javis(demo, [
      BackgroundAction(1:100, ground),
      Action(1:100, :red_ball, (args...)->circ(p1, "red"), subactions = [
              SubAction()
              SubAction()
              SubAction()
          ]
      ),
  ]
)
```

I think readability-wise, this makes a lot of sense. What do you think?

**Comment by Wikunia** [comment]
I see that you like `kwarg` :smile: 
Somehow I went for just joining them together as it's currently done with transformations but yeah this might be cleaner.

**Comment by Wikunia** [comment]
I think I'll try to implement drawing this: 
https://upload.wikimedia.org/wikipedia/commons/f/f0/Haus_vom_Nikolaus_eulerian_hori.webm
(one of them with something like this code)
```
 function ground(args...) 
    background("white")
    sethue("black")
end

function house_of_nicholas(p1=O, width=100, color="black")
    # sethue(color)
    #     .p1
    # .p2   .p3
    #
    # .p4   .p5
    width2 = div(width, 2)
    p2 = p1 + Point(-width2, width2)
    p3 = p1 + Point(width2, width2)
    p4 = p2 + Point(0, width)
    p5 = p3 + Point(0, width)
    line(p4, p5, :stroke)
    line(p5, p2, :stroke)
    line(p2, p4, :stroke)
    line(p4, p3, :stroke)
    line(p3, p1, :stroke)
    line(p1, p2, :stroke)
    line(p2, p3, :stroke)
    line(p3, p5, :stroke)
end

function anim_house_of_nicholas()
    demo = Video(500, 500)
    javis(demo, [
        BackgroundAction(1:100, ground),
        Action(1:100, (args...)->house_of_nicholas(); subactions = [
              SubAction(1:50, appear(:animate_stroke)),
              SubAction(91:100, disappear(:fade))
          ])
    ], pathname="current/nicholas.gif")
end
```

to draw something like this (+ disappear action)
![nicholas](https://user-images.githubusercontent.com/4931746/89867735-e96ab400-dbb1-11ea-9e01-5ca8034841c9.gif)

It should also account for the length of the `line` but that I didn't wanna do that by hand :smile:
